const WIZARD_KEY = "hatcommways_event_wizard";
const CREATED_KEY = "hatcommways_created_event";
const EVENT_IDEMPOTENCY_KEY = "hatcommways_event_create_idempotency";
const participantOptions = ["Community Members","Volunteers","Students","Families","Organizations","Local Businesses","Experts / Specialists","Other"];
let wizardStep = 1;

function wizardValues(form) { const data = Object.fromEntries(new FormData(form)); data.participants = [...form.querySelectorAll('[name="participants"]:checked')].map(x=>x.value); return data; }
function saveWizard(form) { sessionStorage.setItem(WIZARD_KEY, JSON.stringify(wizardValues(form))); }
function restoreWizard(form) { const saved=JSON.parse(sessionStorage.getItem(WIZARD_KEY)||"null"); if(!saved)return; Object.entries(saved).forEach(([k,v])=>{ if(k==="participants") return v.forEach(x=>form.querySelector(`[name="participants"][value="${CSS.escape(x)}"]`)?.click()); const fields=form.querySelectorAll(`[name="${k}"]`); fields.forEach(f=>{ if(f.type==="radio") f.checked=f.value===v; else f.value=v??""; }); }); }
function setStep(step) { wizardStep=step; document.querySelectorAll('.wizard-step').forEach(x=>x.classList.toggle('is-active',+x.dataset.step===step)); document.querySelectorAll('#stepper li').forEach((x,i)=>{x.classList.toggle('is-active',i+1===step);x.classList.toggle('is-complete',i+1<step)}); document.querySelector('#progress-step').textContent=step; document.querySelector('#progress-fill').style.width=`${step*25}%`; document.querySelector('#back-step').hidden=step===1; document.querySelector('#skip-context').hidden=step!==3; document.querySelector('#continue-step').hidden=step===4; document.querySelector('#create-event').hidden=step!==4; if(step===4) renderReview(); window.scrollTo({top:0,behavior:'smooth'}); }
function visibleValid() { const section=document.querySelector(`.wizard-step[data-step="${wizardStep}"]`); const invalid=[...section.querySelectorAll('[required]')].find(x=>!x.checkValidity()); if(invalid){invalid.reportValidity();return false} if(wizardStep===2){const f=document.querySelector('#event-wizard'); const start=new Date(`${f.startDate.value}T${f.startTime.value}`),end=new Date(`${f.endDate.value}T${f.endTime.value}`); if(end<=start){document.querySelector('#time-error').textContent='End date and time must be after the start.';return false} document.querySelector('#time-error').textContent='';} return true; }
function renderReview(){const d=wizardValues(document.querySelector('#event-wizard')); const category=d.category==='Other'?d.customCategory:d.category; const location=d.format==='Online'?'Online':`${d.venue}, ${d.city}, ${d.region}, ${d.country}`; const sections=[['Basics',`<b>${d.name}</b><span>${d.shortPurpose}</span><span>${category}</span>`],['When & Where',`<span>${d.format}</span><span>${location}</span><span>${d.startDate} ${d.startTime} — ${d.endDate} ${d.endTime}</span><span>${d.timezone}</span>`],['Context',`<span>${d.detailedPurpose}</span><span>${d.scale?`Expected scale: ${d.scale}`:'Scale not specified'}</span><span>${d.participants?.join(', ')||'Participants not specified'}</span>`]]; document.querySelector('#review-summary').innerHTML=sections.map((x,i)=>`<article><button type="button" data-edit="${i+1}">Edit</button><h3>${x[0]}</h3>${x[1]}</article>`).join(''); document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>setStep(+b.dataset.edit));}
function iso(date,time,tz){const suffix=tz==='Asia/Kolkata'?'+05:30':'Z';return `${date}T${time}:00${suffix}`;}

const wizard=document.querySelector('#event-wizard');
if(wizard){const host=document.querySelector('#participants');participantOptions.forEach(x=>host.insertAdjacentHTML('beforeend',`<label><input type="checkbox" name="participants" value="${x}"><span>${x}</span></label>`));restoreWizard(wizard); const updateConditions=()=>{const other=wizard.querySelector('[name="category"][value="Other"]').checked;wizard.customCategory.hidden=!other;wizard.customCategory.required=other;const online=wizard.format.value==='Online';document.querySelector('#physical-location').hidden=online;document.querySelector('#location-preview').hidden=online;['venue','city','region','country'].forEach(n=>wizard[n].required=!online);wizard.customParticipant.hidden=![...wizard.querySelectorAll('[name="participants"]:checked')].some(x=>x.value==='Other');};wizard.addEventListener('change',()=>{updateConditions();saveWizard(wizard)});wizard.addEventListener('input',()=>saveWizard(wizard));updateConditions();document.querySelector('#continue-step').onclick=()=>{if(visibleValid())setStep(wizardStep+1)};document.querySelector('#back-step').onclick=()=>setStep(wizardStep-1);document.querySelector('#skip-context').onclick=()=>{if(wizard.detailedPurpose.checkValidity())setStep(4);else wizard.detailedPurpose.reportValidity()};wizard.addEventListener('submit',async e=>{e.preventDefault();if(wizardStep!==4)return;if(!visibleValid())return;const d=wizardValues(wizard);const button=document.querySelector('#create-event');button.disabled=true;try{const event=await api('/events',{method:'POST',body:JSON.stringify({name:d.name.trim(),purpose:d.shortPurpose.trim(),event_type:d.format,starts_at:iso(d.startDate,d.startTime,d.timezone),ends_at:iso(d.endDate,d.endTime,d.timezone),timezone:d.timezone,location_description:d.format==='Online'?'Online':`${d.venue}, ${d.city}, ${d.region}, ${d.country}`,idempotency_key:sessionStorage.getItem(EVENT_IDEMPOTENCY_KEY)||(()=>{const key=crypto.randomUUID();sessionStorage.setItem(EVENT_IDEMPOTENCY_KEY,key);return key})()})});const account=await api('/auth/me');sessionStorage.setItem(CREATED_KEY,JSON.stringify({event,form:d,createdBy:account.display_name}));sessionStorage.removeItem(WIZARD_KEY);sessionStorage.removeItem(EVENT_IDEMPOTENCY_KEY);location.assign('./event-created.html');}catch(err){showMessage(document.querySelector('#create-error'),err.message);button.disabled=false;}});}

const success=document.querySelector('#success-page');
if(success){(async()=>{if(!getToken()){location.replace('./signin.html');return}try{await api('/auth/me');const saved=JSON.parse(sessionStorage.getItem(CREATED_KEY)||'null');if(!saved){location.replace('./app.html');return}const {event,form,createdBy}=saved;success.querySelector('#success-summary').innerHTML=`<h2>Event Summary</h2><dl><div><dt>Event Name</dt><dd>${event.name}</dd></div><div><dt>Category</dt><dd>${form.category==='Other'?form.customCategory:form.category}</dd></div><div><dt>Date/Time</dt><dd>${form.startDate} ${form.startTime} — ${form.endDate} ${form.endTime}</dd></div><div><dt>Location</dt><dd>${event.location_description}</dd></div><div><dt>Created By</dt><dd>${createdBy}</dd></div></dl>`;success.querySelector('#continue-planning').href=`./planning.html?event=${event.id}`;success.querySelector('#view-created-event').href=`./event.html?id=${event.id}`;success.hidden=false;}catch{clearToken();location.replace('./signin.html')}})();}
