const homeParams=new URLSearchParams(location.search);const homeEventId=homeParams.get('id')||homeParams.get('event');const homeRoot=document.querySelector('#event-home');let homeData;
const homeEsc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const dateTime=value=>new Date(value).toLocaleString([],{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'});
function empty(host,copy){host.innerHTML=`<p class="is-empty">${homeEsc(copy)}</p>`}
function renderHeader(){const {event,setup,account}=homeData;document.querySelector('#home-name').textContent=account.display_name;document.querySelector('#home-type').textContent=account.account_type==='ORGANIZATION'?'Organization':'Individual';document.querySelector('#home-avatar').textContent=account.display_name.charAt(0).toUpperCase();document.querySelector('#event-name').textContent=event.name;document.querySelector('#event-tagline').textContent=event.purpose;document.querySelector('#event-location').textContent=`⌖ ${event.location_description}`;document.querySelector('#event-date').textContent=`▣ ${dateTime(event.starts_at)}`;document.querySelector('#event-visibility').textContent=`♧ ${setup.privacy_settings.event_visibility}`;document.querySelector('#manage-event').href=`./event-setup.html?event=${encodeURIComponent(homeEventId)}`;const sponsors=document.querySelector('#header-sponsors');const visible=setup.sponsors_support.filter(item=>item.visibility_enabled);if(!visible.length)empty(sponsors,'No public supporters configured');else sponsors.innerHTML=visible.map(item=>`<span>${item.type==='SPONSOR'?'◆':'♡'} ${homeEsc(item.name)}</span>`).join('')}
function renderOverview(){const {event,stages,account}=homeData;const context=event.planning_context||{};document.querySelector('#about-event').textContent=context.detailed_purpose||event.purpose;const theme=context.custom_theme||context.theme;document.querySelector('#event-theme').textContent=theme?`Naming style: ${theme}`:'Planning vocabulary follows the event’s selected presentation style.';const goals=[];if(context.desired_outcomes)goals.push(['Desired outcomes',context.desired_outcomes]);if(context.expected_scale)goals.push(['Expected scale',String(context.expected_scale)]);if(context.known_requirements)goals.push(['Known requirements',context.known_requirements]);const goalHost=document.querySelector('#event-goals');if(!goals.length)empty(goalHost,'No additional goals were configured.');else goalHost.innerHTML=goals.map(([name,value])=>`<div class="goal"><strong>${homeEsc(name)}</strong><small>${homeEsc(value)}</small></div>`).join('');const timeline=document.querySelector('#event-timeline');if(!stages.length)empty(timeline,'No confirmed stages yet.');else timeline.innerHTML=stages.map(stage=>`<li><strong>${homeEsc(stage.canonical_name)}</strong><small>${homeEsc(dateTime(stage.starts_at))} — ${homeEsc(dateTime(stage.ends_at))}</small></li>`).join('');document.querySelector('#organizer-name').textContent=account.display_name;document.querySelector('#safety-note').textContent=context.constraints||'No organizer safety or route constraint has been recorded.'}
function renderJoining(){const {event,setup}=homeData;document.querySelector('#joining-window').textContent=`${dateTime(event.starts_at)} — ${dateTime(event.ends_at)}`;document.querySelector('#joining-location').textContent=event.location_description;document.querySelector('#joining-map-status').textContent=setup.map_settings.map_enabled?`Enabled · ${setup.map_settings.participation_dimensions.join(', ')||'no dimensions selected'}`:'Disabled by organizer'}
function renderResources(){const {setup}=homeData;const resources=document.querySelector('#resource-list');if(!setup.resources.length)empty(resources,'No resource needs configured.');else resources.innerHTML=setup.resources.map(item=>`<div class="data-row"><div><strong>${homeEsc(item.name)}</strong><small>${homeEsc(item.category||item.note||'Event resource need')}</small></div><b>${item.quantity==null?'Quantity not set':`${homeEsc(item.quantity)} ${homeEsc(item.unit||'')}`}</b></div>`).join('');const sponsors=document.querySelector('#sponsor-list');const visible=setup.sponsors_support.filter(item=>item.visibility_enabled);if(!visible.length)empty(sponsors,'No visible sponsors or support partners.');else sponsors.innerHTML=visible.map(item=>`<div class="data-row"><div><strong>${homeEsc(item.name)}</strong><small>${homeEsc(item.description||item.type.replace('_',' '))}</small></div><b>${homeEsc(item.type.replace('_',' '))}</b></div>`).join('')}
function renderPayments(){const visible=homeData.setup.contribution_links.filter(item=>item.visibility_enabled);const host=document.querySelector('#payment-list');if(!visible.length)empty(host,'No external contribution links are visible.');else host.innerHTML=visible.map(item=>`<div class="data-row"><div><strong>${homeEsc(item.label)}</strong><small>${homeEsc(item.provider||item.purpose||'External contribution link')}</small></div><a href="${homeEsc(item.external_url)}" target="_blank" rel="noopener noreferrer">Open external link ↗</a></div>`).join('')}
function renderAll(){document.querySelector('.published-badge').textContent=homeData.stages.length?'Plan confirmed':'Planning';renderHeader();renderOverview();renderJoining();renderResources();renderPayments()}
document.querySelectorAll('.event-tabs button').forEach(button=>button.onclick=()=>{document.querySelectorAll('.event-tabs button').forEach(item=>item.classList.toggle('is-active',item===button));document.querySelectorAll('.tab-panel').forEach(panel=>{const active=panel.id===`tab-${button.dataset.tab}`;panel.hidden=!active})});
async function initializeEventHome(){if(!getToken()||!homeEventId){location.replace('./signin.html');return}try{const [account,workspace,setup]=await Promise.all([api('/auth/me'),api(`/events/${homeEventId}/stage-plan-workspace`),api(`/events/${homeEventId}/setup`)]);homeData={account,event:workspace.event,stages:workspace.stages,setup};renderAll();homeRoot.hidden=false}catch(error){document.querySelector('#event-error').textContent=error.message;homeRoot.hidden=false}}
initializeEventHome();
