const params=new URLSearchParams(location.search),eventId=params.get('event');let stageId=params.get('id'),loadVersion=0,switching=false;
const root=document.querySelector('#inside-stage');let data,selectedWorkRef=null;
const esc=value=>String(value??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function position(start,end,windowStart,windowEnd){const total=new Date(windowEnd)-new Date(windowStart);return{left:Math.max(0,(new Date(start)-new Date(windowStart))/total*100),width:Math.max(1,(new Date(end)-new Date(start))/total*100)}}
const shortDate=value=>new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short'}).format(new Date(value));
const shortTime=value=>new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',hour:'numeric',minute:'2-digit'}).format(new Date(value));
function axisLabels(start,end){const from=new Date(start),to=new Date(end),labels=[];for(let index=0;index<5;index++){const point=new Date(from.getTime()+((to-from)*index/4));labels.push(`<span>${esc(shortTime(point))}</span>`)}return labels.join('')}
async function initialize(){if(!getToken()||!eventId||!stageId){location.replace('./signin.html');return}try{const [account,workspace]=await Promise.all([api('/auth/me'),loadWorkspace()]);data=workspace;document.querySelector('#inside-name').textContent=account.display_name;document.querySelector('#inside-type').textContent=account.account_type==='ORGANIZATION'?'Organization':'Individual';document.querySelector('#inside-avatar').textContent=account.display_name.charAt(0).toUpperCase();document.querySelector('#back-stage-plan').href=`./planning.html?event=${encodeURIComponent(eventId)}`;render();root.hidden=false;if(['REQUESTED','RUNNING'].includes(data.mode))pollExistingRequest()}catch(error){showError(error)}}
const loadWorkspace=(id=stageId)=>api(`/events/${eventId}/stages/${id}/work-design-workspace`);
async function pollExistingRequest(version=loadVersion,id=stageId){try{for(let attempt=0;attempt<40&&['REQUESTED','RUNNING'].includes(data.mode);attempt++){await new Promise(resolve=>setTimeout(resolve,1500));if(version!==loadVersion)return;const next=await loadWorkspace(id);if(version!==loadVersion)return;data=next;render()}}catch(error){if(version===loadVersion)showError(error)}}
function syncSaveExit(){document.querySelector('#save-and-exit')?.remove();installSaveExit(eventId,'WORK_DESIGN',stageId)}
function setSwitching(value){switching=value;document.querySelector('.inside-layout').setAttribute('aria-busy',String(value));['#generate-work','#side-action','#confirm-work','#save-and-exit'].forEach(selector=>{const button=document.querySelector(selector);if(button)button.disabled=value})}
async function switchStage(id,fromHistory=false){if(!id)return;if(id===stageId&&!switching)return;const version=++loadVersion;setSwitching(true);document.querySelector('#inside-message').textContent='Loading selected stage…';try{const next=await loadWorkspace(id);if(version!==loadVersion)return;stageId=id;data=next;selectedWorkRef=null;if(!fromHistory)history.pushState(null,'',`./stage.html?id=${encodeURIComponent(stageId)}&event=${encodeURIComponent(eventId)}`);render();syncSaveExit();document.querySelector('#inside-message').textContent='';setSwitching(false);if(['REQUESTED','RUNNING'].includes(data.mode))pollExistingRequest(version,id)}catch(error){if(version!==loadVersion)return;if(fromHistory)history.replaceState(null,'',`./stage.html?id=${encodeURIComponent(stageId)}&event=${encodeURIComponent(eventId)}`);setSwitching(false);showError(error);if(['REQUESTED','RUNNING'].includes(data.mode))pollExistingRequest(version,stageId)}}
window.addEventListener('popstate',()=>switchStage(new URLSearchParams(location.search).get('id'),true));

function render(){renderStageContext();renderSummary();const mode=data.mode;root.dataset.mode=mode;document.querySelector('#work-status').textContent=({EMPTY:'Work Design Not Started',REQUESTED:'Work Design Requested',RUNNING:'Work Design In Progress',PROPOSAL:'Work Proposal Ready',CONFIRMED:'Work Confirmed',FAILED:'Work Design Failed'})[mode]||mode;document.querySelector('.work-card').dataset.mode=mode;const actorAction=document.querySelector('#design-actors'),confirmAction=document.querySelector('#confirm-work');actorAction.hidden=mode!=='CONFIRMED';actorAction.href=`./actor-tree.html?event=${encodeURIComponent(eventId)}`;confirmAction.hidden=mode!=='PROPOSAL';document.querySelector('#generate-work').hidden=mode!=='EMPTY';if(mode==='PROPOSAL')renderWork(data.proposal.payload.proposed_work);else if(mode==='CONFIRMED')renderWork(data.work.map(item=>({temporary_work_ref:item.id,canonical_name:item.canonical_name,purpose:item.purpose,estimated_person_hours:item.estimated_person_hours,work_share:item.work_share,proposed_start:item.starts_at,proposed_end:item.ends_at,dependencies:item.dependency_work_ids})));else renderEmpty(mode)}
function renderStageContext(){const host=document.querySelector('#compact-stage-list'),timeline=document.querySelector('#compact-timeline');host.innerHTML='';timeline.innerHTML='';const colors=['green','blue','violet','orange','teal'];data.stages.forEach((stage,index)=>{const duration=Math.max(1,new Date(stage.ends_at)-new Date(stage.starts_at)),card=document.createElement('div');card.className=`compact-stage ${stage.id===stageId?'is-selected':''} tone-${colors[index%colors.length]}`;card.style.setProperty('--stage-grow',duration);card.setAttribute('role','link');card.tabIndex=0;card.setAttribute('aria-current',stage.id===stageId?'page':'false');card.setAttribute('aria-label',`Open Stage ${stage.stage_order}: ${stage.canonical_name}`);card.innerHTML=`<div><span>${index+1}</span><strong>${esc(stage.canonical_name)}</strong></div><small>${esc(shortDate(stage.starts_at))} – ${esc(shortDate(stage.ends_at))}</small>`;const open=()=>{if(stage.id!==stageId||switching)switchStage(stage.id)};card.onclick=open;card.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();open()}};host.append(card)});const selected=data.selected_stage;document.querySelector('#inside-title').textContent=`Inside Stage ${selected.stage_order} — ${selected.canonical_name}`;document.querySelector('#inside-meta').textContent=`Stage time: ${shortTime(selected.starts_at)} — ${shortTime(selected.ends_at)}   ·   Total work items: ${data.mode==='PROPOSAL'?data.proposal.payload.proposed_work.length:data.work.length}`;document.querySelector('#time-axis').innerHTML=axisLabels(selected.starts_at,selected.ends_at)}
function renderSummary(){const s=data.selected_stage,count=data.mode==='PROPOSAL'?data.proposal.payload.proposed_work.length:data.work.length;const rows=[['Selected Stage',`${s.stage_order}. ${s.canonical_name}`],['Stage Time',`${new Date(s.starts_at).toLocaleString()} — ${new Date(s.ends_at).toLocaleString()}`],['Work Items',count],['Stage Version',s.version]];document.querySelector('#stage-summary').innerHTML=rows.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join('')}
function renderEmpty(mode){document.querySelector('#work-table').hidden=true;document.querySelector('#work-detail-panel').hidden=true;selectedWorkRef=null;const empty=document.querySelector('#empty-work');empty.hidden=false;const title=empty.querySelector('h3'),copy=empty.querySelector('p'),button=document.querySelector('#generate-work');if(mode==='REQUESTED'||mode==='RUNNING'){title.textContent='Work Design request is in progress';copy.textContent='The request exists, but no proposal is available yet.';button.hidden=true}else if(mode==='FAILED'){title.textContent='Work Design could not be generated';copy.textContent='The existing request failed. No authoritative work was created.';button.hidden=true}else{title.textContent='Ready to design work inside this stage?';copy.textContent='Work Design runs only when you explicitly request it.';button.hidden=false}document.querySelector('#next-copy').textContent=mode==='EMPTY'?'Generate a proposal when you are ready.':copy.textContent;syncSideAction(button.hidden)}
function renderWork(items){document.querySelector('#empty-work').hidden=true;document.querySelector('#work-table').hidden=false;const host=document.querySelector('#work-rows'),stage=data.selected_stage,tones=['green','blue','violet','orange','teal'];if(!items.some(item=>item.temporary_work_ref===selectedWorkRef))selectedWorkRef=null;host.innerHTML='';items.forEach((item,index)=>{const box=position(item.proposed_start,item.proposed_end,stage.starts_at,stage.ends_at),selected=item.temporary_work_ref===selectedWorkRef;const row=document.createElement('article');row.className=`work-item tone-${tones[index%tones.length]}${selected?' selected-work':''}`;row.innerHTML=`<div class="work-row-main timeline-grid work-row"><div class="work-name"><button type="button" aria-expanded="${selected}">${selected?'⌄':'›'}</button><i class="work-dot"></i><strong>${esc(item.canonical_name)}</strong></div><span class="work-share">${Number(item.work_share).toFixed(2)}%</span><div class="work-track"><span class="work-bar" style="left:${box.left}%;width:${box.width}%"></span></div></div>`;row.querySelector('button').onclick=()=>{selectedWorkRef=selected?null:item.temporary_work_ref;renderWork(items)};host.append(row)});renderWorkDetail(items.find(item=>item.temporary_work_ref===selectedWorkRef));document.querySelector('#next-copy').textContent=data.mode==='CONFIRMED'?'This Work Design is confirmed and preserved. Continue to Actor Requirements.':'Review the pending proposal before confirming it.';syncSideAction(true)}
function renderWorkDetail(item){const panel=document.querySelector('#work-detail-panel');if(!item){panel.hidden=true;panel.innerHTML='';return}const dependencies=item.dependencies?.length?item.dependencies.map(esc).join(', '):'None';panel.hidden=false;panel.innerHTML=`<header class="detail-header"><div class="work-name"><i class="work-dot"></i><strong>${esc(item.canonical_name)}</strong></div><strong>${Number(item.work_share).toFixed(2)}%</strong><button type="button" disabled aria-label="More work actions unavailable">•••</button></header><nav class="detail-tabs" aria-label="Work details"><button type="button" class="active">Overview</button><button type="button" disabled>Resources</button><button type="button" disabled>Requirements</button><button type="button" disabled>Constraints</button><button type="button" disabled>Coordination</button></nav><div class="detail-content"><section class="detail-column"><h4>Description</h4><p>${esc(item.purpose)}</p></section><section class="detail-column"><h4>Depends On</h4><p>${dependencies}</p></section><section class="detail-column"><h4>Estimated Effort</h4><p><strong>${Number(item.estimated_person_hours)} person-hours</strong></p></section><section class="detail-column"><h4>Scheduled Time</h4><p>${esc(shortTime(item.proposed_start))}<br>${esc(shortTime(item.proposed_end))}</p></section></div>`}
function syncSideAction(hide){const side=document.querySelector('#side-action');side.hidden=hide;if(!hide)side.onclick=()=>document.querySelector('#generate-work').click()}
async function requestWork(){if(switching||data.mode!=='EMPTY')return;const version=loadVersion,id=stageId;const buttons=[document.querySelector('#generate-work'),document.querySelector('#side-action')];buttons.forEach(button=>button.disabled=true);try{await api(`/stages/${stageId}/work-design-requests`,{method:'POST',body:JSON.stringify({event_id:eventId,expected_event_version:data.event.version,expected_stage_version:data.selected_stage.version,idempotency_key:`work-design:${stageId}`})});if(version!==loadVersion)return;const next=await loadWorkspace(id);if(version!==loadVersion)return;data=next;render();if(['REQUESTED','RUNNING'].includes(data.mode))pollExistingRequest()}catch(error){if(version!==loadVersion)return;showError(error);buttons.forEach(button=>button.disabled=false)}}
async function confirmWork(){if(switching||data.mode!=='PROPOSAL')return;const version=loadVersion,id=stageId;const button=document.querySelector('#confirm-work');button.disabled=true;try{const result=await api(`/work-proposals/${data.proposal.id}/decision`,{method:'POST',body:JSON.stringify({decision:'APPROVE',decision_idempotency_key:`approve-work:${data.proposal.id}`})});if(version!==loadVersion)return;if(result.status!=='APPROVED')throw new Error('Work Design was not saved. The proposal needs review.');const workspaces=await Promise.all(data.stages.map(stage=>loadWorkspace(stage.id)));if(version!==loadVersion)return;const incomplete=workspaces.find(workspace=>workspace.mode!=='CONFIRMED');if(incomplete){await switchStage(incomplete.selected_stage.id);return}await api(`/events/${eventId}/resume-state`,{method:'PUT',body:JSON.stringify({current_phase:'ACTOR_REQUIREMENTS',last_open_stage_id:null})});location.assign(`./actor-tree.html?event=${encodeURIComponent(eventId)}`)}catch(error){if(version!==loadVersion)return;showError(error);button.disabled=false}}
document.querySelector('#generate-work').onclick=requestWork;document.querySelector('#side-action').onclick=requestWork;
document.querySelector('#confirm-work').onclick=confirmWork;
document.querySelector('#design-actors').onclick=async event=>{event.preventDefault();if(data.mode!=='CONFIRMED')return;const target=`./actor-tree.html?event=${encodeURIComponent(eventId)}`;try{await api(`/events/${eventId}/resume-state`,{method:'PUT',body:JSON.stringify({current_phase:'ACTOR_REQUIREMENTS',last_open_stage_id:null})});location.assign(target)}catch(error){showError(error)}};
function showError(error){const host=document.querySelector('#inside-message');host.textContent=error.message;root.hidden=false}
initialize();
syncSaveExit();
