const params=new URLSearchParams(location.search),eventId=params.get('event'),stageId=params.get('id');
const root=document.querySelector('#inside-stage');let data;
const esc=value=>String(value??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function position(start,end,windowStart,windowEnd){const total=new Date(windowEnd)-new Date(windowStart);return{left:Math.max(0,(new Date(start)-new Date(windowStart))/total*100),width:Math.max(1,(new Date(end)-new Date(start))/total*100)}}
async function initialize(){if(!getToken()||!eventId||!stageId){location.replace('./signin.html');return}try{const [account,workspace]=await Promise.all([api('/auth/me'),api(`/events/${eventId}/stages/${stageId}/work-design-workspace`)]);data=workspace;document.querySelector('#inside-name').textContent=account.display_name;document.querySelector('#inside-type').textContent=account.account_type==='ORGANIZATION'?'Organization':'Individual';document.querySelector('#inside-avatar').textContent=account.display_name.charAt(0).toUpperCase();document.querySelector('#back-stage-plan').href=`./planning.html?event=${encodeURIComponent(eventId)}`;render();root.hidden=false}catch(error){showError(error)}}
function render(){renderStageContext();renderSummary();const mode=data.mode;document.querySelector('#work-status').textContent=({EMPTY:'Work Design Not Started',REQUESTED:'Work Design Requested',RUNNING:'Work Design In Progress',PROPOSAL:'Work Proposal Ready',CONFIRMED:'Work Confirmed',FAILED:'Work Design Failed'})[mode]||mode;document.querySelector('.work-card').dataset.mode=mode;if(mode==='PROPOSAL')renderWork(data.proposal.payload.proposed_work);else if(mode==='CONFIRMED')renderWork(data.work.map(item=>({temporary_work_ref:item.id,canonical_name:item.canonical_name,purpose:item.purpose,estimated_person_hours:item.estimated_person_hours,work_share:item.work_share,proposed_start:item.starts_at,proposed_end:item.ends_at,dependencies:item.dependency_work_ids})));else renderEmpty(mode)}
function renderStageContext(){const host=document.querySelector('#compact-stage-list'),timeline=document.querySelector('#compact-timeline'),e=data.event;host.innerHTML='';timeline.innerHTML='';data.stages.forEach((stage,index)=>{host.insertAdjacentHTML('beforeend',`<div class="compact-stage ${stage.id===stageId?'is-selected':''}"><span>${index+1}</span><span>${esc(stage.canonical_name)}</span></div>`);const box=position(stage.starts_at,stage.ends_at,e.starts_at,e.ends_at),bar=document.createElement('div');bar.className=`compact-bar ${stage.id===stageId?'is-selected':''}`;bar.style.cssText=`left:${box.left}%;width:${box.width}%;top:${25+index*30}px`;timeline.append(bar)});const selected=data.selected_stage;document.querySelector('#inside-title').textContent=`Inside Stage ${selected.stage_order} — ${selected.canonical_name}`}
function renderSummary(){const s=data.selected_stage,count=data.mode==='PROPOSAL'?data.proposal.payload.proposed_work.length:data.work.length;const rows=[['Selected Stage',`${s.stage_order}. ${s.canonical_name}`],['Stage Time',`${new Date(s.starts_at).toLocaleString()} — ${new Date(s.ends_at).toLocaleString()}`],['Work Items',count],['Stage Version',s.version]];document.querySelector('#stage-summary').innerHTML=rows.map(([a,b])=>`<div><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join('')}
function renderEmpty(mode){document.querySelector('#work-table').hidden=true;const empty=document.querySelector('#empty-work');empty.hidden=false;const title=empty.querySelector('h3'),copy=empty.querySelector('p'),button=document.querySelector('#generate-work');if(mode==='REQUESTED'||mode==='RUNNING'){title.textContent='Work Design request is in progress';copy.textContent='The request exists, but no proposal is available yet.';button.hidden=true}else if(mode==='FAILED'){title.textContent='Work Design could not be generated';copy.textContent='The existing request failed. No authoritative work was created.';button.hidden=true}else{title.textContent='Ready to design work inside this stage?';copy.textContent='Work Design runs only when you explicitly request it.';button.hidden=false}syncSideAction(button.hidden)}
function renderWork(items){document.querySelector('#empty-work').hidden=true;document.querySelector('#work-table').hidden=false;const host=document.querySelector('#work-rows'),stage=data.selected_stage;host.innerHTML='';items.forEach(item=>{const box=position(item.proposed_start,item.proposed_end,stage.starts_at,stage.ends_at),row=document.createElement('article');row.innerHTML=`<div class="work-row-main"><div class="work-name"><button type="button" aria-expanded="false">›</button><strong>${esc(item.canonical_name)}</strong></div><span class="work-share">${Number(item.work_share).toFixed(2)}%</span><div class="work-track"><span class="work-bar" style="left:${box.left}%;width:${box.width}%"></span></div></div><div class="work-details" hidden><div><h4>Overview</h4><p>${esc(item.purpose)}</p><p>${Number(item.estimated_person_hours)} estimated person-hours</p></div><div><h4>Dependencies</h4><p>${item.dependencies?.length?item.dependencies.map(esc).join(', '):'None'}</p></div><div class="unavailable"><h4>Resources</h4><p>Not included in the current proposal contract.</p></div><div class="unavailable"><h4>Requirements</h4><p>Not included in the current proposal contract.</p></div><div class="unavailable"><h4>Constraints / Coordination</h4><p>Not included in the current proposal contract.</p></div></div>`;const toggle=row.querySelector('button'),details=row.querySelector('.work-details');toggle.onclick=()=>{details.hidden=!details.hidden;toggle.textContent=details.hidden?'›':'⌄';toggle.setAttribute('aria-expanded',String(!details.hidden))};host.append(row)});document.querySelector('#next-copy').textContent=data.mode==='CONFIRMED'?'Work is authoritative. Actor Requirements are a future next step.':'Review the real pending proposal. Confirmation is handled by the existing work decision contract.';syncSideAction(true)}
function syncSideAction(hide){const side=document.querySelector('#side-action');side.hidden=hide;if(!hide)side.onclick=()=>document.querySelector('#generate-work').click()}
async function requestWork(){const buttons=[document.querySelector('#generate-work'),document.querySelector('#side-action')];buttons.forEach(button=>button.disabled=true);try{await api(`/stages/${stageId}/work-design-requests`,{method:'POST',body:JSON.stringify({event_id:eventId,expected_event_version:data.event.version,expected_stage_version:data.selected_stage.version,idempotency_key:`work-design:${stageId}`})});data=await api(`/events/${eventId}/stages/${stageId}/work-design-workspace`);render()}catch(error){showError(error);buttons.forEach(button=>button.disabled=false)}}
document.querySelector('#generate-work').onclick=requestWork;document.querySelector('#side-action').onclick=requestWork;
function showError(error){const host=document.querySelector('#inside-message');host.textContent=error.message;root.hidden=false}
initialize();
