const joinEventId=new URLSearchParams(location.search).get('event');const joinRoot=document.querySelector('#join-page');let joinData;let joinStep=1;let advisory;
const jEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const jDate=v=>new Date(v).toLocaleString([],{dateStyle:'medium',timeStyle:'short'});
function showStep(step){joinStep=step;document.querySelectorAll('.join-screen').forEach(x=>x.hidden=Number(x.dataset.step)!==step);document.querySelectorAll('.join-steps span').forEach((x,i)=>x.classList.toggle('active',i<step));document.querySelector('#join-intro').textContent=step===1?'Be part of the change. Choose how you want to contribute to this event.':step===2?'Tell us when you are available. This helps us match you with the right work.':'Review your request and advisory before submitting.'}
function selected(){return[...document.querySelectorAll('[data-role]:checked')].map(input=>({actor_requirement_id:input.dataset.role,preference:document.querySelector(`[data-preference="${input.dataset.role}"]`).value}))}
function optionMarkup(option,checked=false){return`<label class="option-row"><input type="checkbox" data-role="${option.actor_requirement_id}" ${checked?'checked':''}><span><strong>${jEsc(option.work_name)} — ${jEsc(option.role_name)}</strong><small>${jEsc(option.responsibility_summary)}</small><small>${jDate(option.starts_at)}–${jDate(option.ends_at)} · Required ${option.minimum_required_count} · Accepted ${option.accepted_count} · Remaining ${option.remaining_count}</small></span><select data-preference="${option.actor_requirement_id}"><option value="PREFERRED">Preferred</option><option value="CAN_ALSO_HELP">Can also help</option></select></label>`}
function renderOptions(){const groups=joinData.options.reduce((all,x)=>{const key=`${x.stage_order}. ${x.stage_name}`;(all[key]??=[]).push(x);return all},{});document.querySelector('#join-options').innerHTML=Object.entries(groups).map(([stage,items])=>`<section class="work-group"><h3>${jEsc(stage)}</h3>${items.map(x=>optionMarkup(x)).join('')}</section>`).join('')||'<p>No confirmed role requirements are available.</p>'}
function renderSelected(hostId){const ids=new Set(selected().map(x=>x.actor_requirement_id));const host=document.querySelector(hostId);const options=joinData.options.filter(x=>ids.has(x.actor_requirement_id));host.innerHTML=options.map(x=>`<article class="option-row"><span></span><span><strong>${jEsc(x.work_name)} — ${jEsc(x.role_name)}</strong><small>${jDate(x.starts_at)}–${jDate(x.ends_at)}</small></span><b>${jEsc(document.querySelector(`[data-preference="${x.actor_requirement_id}"]`).selectedOptions[0].textContent)}</b></article>`).join('')}
function availability(){const type=document.querySelector('[name="availability"]:checked').value;return{availability_type:type,availability_start:type==='PARTIAL'?new Date(document.querySelector('#available-from').value).toISOString():null,availability_end:type==='PARTIAL'?new Date(document.querySelector('#available-until').value).toISOString():null,max_commitment_minutes:document.querySelector('#max-commitment').value?Number(document.querySelector('#max-commitment').value):null,allow_alternative_work:document.querySelector('#allow-alternative').checked}}
document.querySelector('#to-availability').onclick=()=>{if(!selected().length){document.querySelector('#join-error').textContent='Select at least one role.';return}document.querySelector('#join-error').textContent='';renderSelected('#selected-options');showStep(2)};
document.querySelectorAll('[name="availability"]').forEach(x=>x.onchange=()=>document.querySelector('#partial-window').hidden=x.value!=='PARTIAL'||!x.checked);
document.querySelectorAll('[data-back]').forEach(x=>x.onclick=()=>showStep(Number(x.dataset.back)));
document.querySelector('#run-advisory').onclick=async()=>{const button=document.querySelector('#run-advisory');button.disabled=true;try{advisory=await api(`/events/${joinEventId}/participation-advisories`,{method:'POST',body:JSON.stringify({selections:selected(),availability:availability()})});document.querySelector('#advisory-status').textContent=advisory.result.overall_advisory.replaceAll('_',' ');document.querySelector('#advisory-explanation').textContent=advisory.result.explanation;document.querySelector('#advisory-findings').innerHTML=advisory.result.findings.map(x=>`<p class="finding ${x.level}">${jEsc(x.message)}</p>`).join('')||'<p class="finding">No timing conflicts detected.</p>';renderSelected('#review-options');showStep(3)}catch(e){document.querySelector('#join-error').textContent=e.message}finally{button.disabled=false}};
document.querySelector('#submit-participation').onclick=async()=>{const button=document.querySelector('#submit-participation');button.disabled=true;try{await api(`/events/${joinEventId}/participation-requests`,{method:'POST',body:JSON.stringify({advisory_id:advisory.id,note:document.querySelector('#join-note').value.trim()||null,idempotency_key:crypto.randomUUID()})});document.querySelectorAll('.join-screen').forEach(x=>x.hidden=true);document.querySelector('#join-complete').hidden=false}catch(e){document.querySelector('#join-error').textContent=e.message;button.disabled=false}};
(async()=>{if(!getToken()||!joinEventId){location.replace('./signin.html');return}try{const [account,data]=await Promise.all([api('/auth/me'),api(`/events/${joinEventId}/join-options`)]);joinData=data;document.querySelector('#join-name').textContent=account.display_name;document.querySelector('#join-avatar').textContent=account.display_name[0].toUpperCase();document.querySelector('#join-event-name').textContent=data.event.name;document.querySelector('#join-event-date').textContent=jDate(data.event.starts_at);document.querySelector('#join-event-location').textContent=data.event.location_description;document.querySelector('#join-event-category').textContent=data.event.category||'Uncategorized';document.querySelector('#join-back').href=`./event.html?event=${encodeURIComponent(joinEventId)}`;renderOptions();joinRoot.hidden=false}catch(e){document.querySelector('#join-error').textContent=e.message;joinRoot.hidden=false}})();
