const meRoot=document.querySelector('#my-events-page');
const meEsc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const phaseLabel=value=>({CREATION_DRAFT:'Creation draft',GOVERNANCE:'Governance',STAGE_PLANNING:'Stage Planning',WORK_DESIGN:'Work Design',ACTOR_REQUIREMENTS:'Actor Requirements',EVENT_SETUP:'Event Setup',READY:'Ready',PUBLISHED:'Published'}[value]||value);
const meAccountTrigger=document.querySelector('#me-account-trigger');
const meAccountPanel=document.querySelector('#me-account-panel');
meAccountTrigger.addEventListener('click',()=>{const open=meAccountPanel.hidden;meAccountPanel.hidden=!open;meAccountTrigger.setAttribute('aria-expanded',String(open))});
document.querySelector('#me-signout').addEventListener('click',()=>{clearToken();location.assign('./index.html')});
document.addEventListener('click',event=>{if(!event.target.closest('.account-menu')){meAccountPanel.hidden=true;meAccountTrigger.setAttribute('aria-expanded','false')}});
function renderMyList(id,items,participating=false){const host=document.querySelector(id);if(!items.length){host.innerHTML=`<div class="empty-events">${participating?'No participating events yet.':'No organizing events yet.'}</div>`;return}host.innerHTML=items.map(item=>`<article class="event-card"><div><h3>${meEsc(item.event_name)}</h3>${item.location?`<p>${meEsc(item.location)}</p>`:''}<span class="phase">${meEsc(phaseLabel(item.current_phase))}</span>${item.current_step?`<small>Step ${item.current_step} of 4</small>`:''}${item.stage_count!=null?`<small>${item.stage_count} stages · ${item.work_count} work items</small>`:''}${item.approved_roles?`<small>Role: ${meEsc(item.approved_roles)}</small>`:''}${participating&&!item.approved_roles?`<small>${item.requested_assignment_count} requested assignment(s)</small>`:''}${item.approved_start?`<small>${new Date(item.approved_start).toLocaleString()} – ${new Date(item.approved_end).toLocaleString()}</small>`:''}<small>Last saved ${new Date(item.last_saved_at).toLocaleString()}</small></div><a class="button button--primary" href="./${meEsc(item.resume_target)}">${participating?'Open My Event':['READY','PUBLISHED'].includes(item.current_phase)?'Open Event':item.current_phase==='CREATION_DRAFT'?'Continue Draft':'Continue'}</a></article>`).join('')}
(async()=>{if(!getToken()){location.replace('./signin.html');return}try{const [account,data]=await Promise.all([api('/auth/me'),api('/me/events')]);document.querySelector('#me-name').textContent=account.display_name;document.querySelector('#me-type').textContent=account.account_type==='ORGANIZATION'?'Organizer':'Individual';document.querySelector('#me-avatar').textContent=account.display_name.charAt(0).toUpperCase();renderMyList('#organizing-events',data.organizing);renderMyList('#participating-events',data.participating,true);meRoot.hidden=false}catch(error){document.querySelector('#my-events-error').textContent=error.message;meRoot.hidden=false}})();
