const eventId=new URLSearchParams(location.search).get('event');
const root=document.querySelector('#stage-workspace');let workspace;let original;let localStages=[];let selectedRef;
const clone=value=>JSON.parse(JSON.stringify(value));
const localDate=value=>{const d=new Date(value);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const iso=value=>new Date(value).toISOString();
const escapeHtml=value=>String(value).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
async function initialize(){if(!getToken()||!eventId){location.replace('./signin.html');return}try{const account=await api('/auth/me');document.querySelector('#workspace-name').textContent=account.display_name;document.querySelector('#workspace-type').textContent=account.account_type==='ORGANIZATION'?'Organization':'Individual';document.querySelector('#workspace-avatar').textContent=account.display_name.charAt(0).toUpperCase();await loadWorkspace()}catch(error){root.hidden=false;showError(error)}}
async function loadWorkspace(){workspace=await api(`/events/${eventId}/stage-plan-workspace`);renderFacts();if(workspace.mode==='CONFIRMED')loadConfirmed();else if(workspace.mode==='PROPOSAL')loadProposal();else renderRequestState();root.hidden=false}
function showPlanChrome(){document.querySelector('.timeline-card').hidden=false;document.querySelector('#stage-editor').closest('section').hidden=false;document.querySelector('.feedback-card').hidden=false;document.querySelector('#reset-plan').hidden=false;document.querySelector('#confirm-stages').hidden=false;document.querySelector('#generate-stage-plan')?.remove()}
function renderRequestState(){const running=workspace.mode==='RUNNING';document.querySelector('.timeline-card').hidden=true;document.querySelector('#stage-editor').closest('section').hidden=true;document.querySelector('.feedback-card').hidden=true;document.querySelector('#reset-plan').hidden=true;document.querySelector('#confirm-stages').hidden=true;document.querySelector('#workspace-title').textContent=running?'Generating Stage Plan':'Plan Your Event Stages';document.querySelector('#workspace-subtitle').textContent=running?'The planning agent is preparing a proposal. You may safely leave and return to this page.':'Generate a proposed stage plan when you are ready.';document.querySelector('#workspace-status').textContent=running?(workspace.planning_request?.status||'Running'):(workspace.mode==='FAILED'?'Previous request failed':'Not requested');const actions=document.querySelector('#workspace-message').closest('section');let button=document.querySelector('#generate-stage-plan');if(!button){button=document.createElement('button');button.id='generate-stage-plan';button.className='confirm-button';button.textContent=workspace.mode==='FAILED'?'Try Again':'Generate Stage Plan';actions.insertBefore(button,document.querySelector('#reset-plan'));button.onclick=requestStagePlan}button.hidden=running;document.querySelector('#workspace-message').textContent=workspace.mode==='FAILED'?'The previous planning request failed. You can explicitly try again.':running?'Stage Plan request is running…':'No Stage Plan has been requested yet.';if(running)setTimeout(pollWorkspace,2000)}
async function pollWorkspace(){try{await loadWorkspace()}catch(error){showError(error)}}
async function requestStagePlan(){const button=document.querySelector('#generate-stage-plan');button.disabled=true;document.querySelector('#workspace-message').textContent='Starting Stage Plan request…';try{await api(`/events/${eventId}/planning-requests`,{method:'POST',body:JSON.stringify({expected_event_version:workspace.event.version,idempotency_key:crypto.randomUUID()})});await loadWorkspace()}catch(error){showError(error);button.disabled=false}}
function renderFacts(){const e=workspace.event;const facts=[['Event',e.name],['Location',e.location_description],['Date',`${new Date(e.starts_at).toLocaleString()} — ${new Date(e.ends_at).toLocaleString()}`],['Timezone',e.timezone],['Event version',e.version]];document.querySelector('#event-facts').innerHTML=facts.map(([a,b])=>`<div><small>${escapeHtml(a)}</small><strong>${escapeHtml(b)}</strong></div>`).join('')}
function loadProposal(){showPlanChrome();root.classList.remove('confirmed');document.querySelector('#workspace-title').textContent='Review & Adjust Stage Plan';document.querySelector('#workspace-subtitle').textContent='AI has prepared a stage plan. Adjust it on the timeline below.';document.querySelector('#workspace-status').textContent='Pending approval';original=clone(workspace.proposal.payload);localStages=clone(original.proposed_stages);selectedRef=localStages[0]?.temporary_stage_ref;render()}
function loadConfirmed(){showPlanChrome();root.classList.add('confirmed');document.querySelector('#workspace-title').textContent='Confirmed Stage Plan';document.querySelector('#workspace-subtitle').textContent='These stages are authoritative. Open a stage when you are ready to design its work.';document.querySelector('#workspace-status').textContent='Confirmed';localStages=workspace.stages.map(s=>({temporary_stage_ref:s.id,canonical_name:s.canonical_name,purpose:s.purpose,proposed_order:s.stage_order,proposed_start:s.starts_at,proposed_end:s.ends_at,dependencies:s.dependency_stage_ids,stage_id:s.id}));selectedRef=localStages[0]?.temporary_stage_ref;renderFacts();render()}
function render(){renderAxis();renderRows();renderEditor()}
function renderAxis(){const start=new Date(workspace.event.starts_at),end=new Date(workspace.event.ends_at),host=document.querySelector('#time-axis');host.innerHTML='';for(let i=0;i<=4;i++){const at=new Date(start.getTime()+(end-start)*i/4);const span=document.createElement('span');span.style.left=`${i*25}%`;span.textContent=at.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});host.append(span)}}
function bounds(stage){const start=new Date(workspace.event.starts_at),end=new Date(workspace.event.ends_at),total=end-start;return{left:Math.max(0,(new Date(stage.proposed_start)-start)/total*100),width:Math.max(1,(new Date(stage.proposed_end)-new Date(stage.proposed_start))/total*100)}}
function renderRows(){const host=document.querySelector('#stage-rows');host.innerHTML='';localStages.sort((a,b)=>a.proposed_order-b.proposed_order).forEach((stage,index)=>{stage.proposed_order=index+1;const row=document.createElement('div');row.className='stage-timeline-row';const box=bounds(stage);row.innerHTML=`<button type="button" class="stage-label"><strong>${index+1}. ${escapeHtml(stage.canonical_name)}</strong><small>${escapeHtml(stage.purpose)}</small></button><div class="stage-track"><button type="button" class="stage-block ${stage.temporary_stage_ref===selectedRef?'is-selected':''}" style="left:${box.left}%;width:${box.width}%"></button></div>`;const block=row.querySelector('.stage-block');row.dataset.stageRef=stage.temporary_stage_ref;block.setAttribute('aria-label',stage.canonical_name);row.querySelector('.stage-label').onclick=block.onclick=()=>selectStage(stage.temporary_stage_ref);if(workspace.mode==='PROPOSAL')enableDrag(block,stage,row.querySelector('.stage-track'));host.append(row)});updateSelection()}
function updateSelection(){document.querySelectorAll('.stage-timeline-row').forEach(row=>{const selected=row.dataset.stageRef===selectedRef;row.classList.toggle('is-selected',selected);row.querySelectorAll('button').forEach(button=>{button.classList.toggle('is-selected',selected);button.setAttribute('aria-pressed',String(selected))})})}
function selectStage(ref){selectedRef=ref;updateSelection();renderEditor()}
function enableDrag(block,stage,track){block.onpointerdown=event=>{event.preventDefault();selectStage(stage.temporary_stage_ref);const resizing=event.offsetX>block.clientWidth-18;const initialX=event.clientX,start=new Date(stage.proposed_start),end=new Date(stage.proposed_end),windowMs=new Date(workspace.event.ends_at)-new Date(workspace.event.starts_at);block.setPointerCapture(event.pointerId);block.onpointermove=move=>{const delta=(move.clientX-initialX)/track.clientWidth*windowMs;if(resizing)stage.proposed_end=new Date(Math.min(new Date(workspace.event.ends_at),Math.max(start.getTime()+60000,end.getTime()+delta))).toISOString();else{const duration=end-start;const next=Math.max(new Date(workspace.event.starts_at).getTime(),Math.min(new Date(workspace.event.ends_at).getTime()-duration,start.getTime()+delta));stage.proposed_start=new Date(next).toISOString();stage.proposed_end=new Date(next+duration).toISOString()}const box=bounds(stage);block.style.left=`${box.left}%`;block.style.width=`${box.width}%`;renderEditor()};block.onpointerup=()=>{block.onpointermove=null}}}
function current(){return localStages.find(s=>s.temporary_stage_ref===selectedRef)}
function renderEditor(){const stage=current(),form=document.querySelector('#stage-editor'),open=document.querySelector('#open-stage');if(!stage){form.hidden=true;open.hidden=true;return}form.hidden=false;form.canonical_name.value=stage.canonical_name;form.purpose.value=stage.purpose;form.proposed_start.value=localDate(stage.proposed_start);form.proposed_end.value=localDate(stage.proposed_end);document.querySelector('#dependency-options').innerHTML=localStages.filter(s=>s.temporary_stage_ref!==stage.temporary_stage_ref).map(s=>`<label><input type="checkbox" value="${escapeHtml(s.temporary_stage_ref)}" ${stage.dependencies.includes(s.temporary_stage_ref)?'checked':''}><span>${escapeHtml(s.canonical_name)}</span></label>`).join('');const confirmed=workspace.mode==='CONFIRMED';form.querySelectorAll('input,textarea').forEach(input=>{input.disabled=confirmed});open.hidden=!confirmed;if(confirmed){open.hidden=false;open.href=`./stage.html?id=${encodeURIComponent(stage.stage_id)}&event=${encodeURIComponent(eventId)}`}}
document.querySelector('#stage-editor').oninput=event=>{const stage=current();if(!stage)return;if(['canonical_name','purpose'].includes(event.target.name))stage[event.target.name]=event.target.value;if(['proposed_start','proposed_end'].includes(event.target.name))stage[event.target.name]=iso(event.target.value);renderRows()};
document.querySelector('#dependency-options').onchange=()=>{current().dependencies=[...document.querySelectorAll('#dependency-options input:checked')].map(x=>x.value)};
document.querySelector('#add-stage').onclick=()=>{const ref=`manual-${crypto.randomUUID()}`;localStages.push({temporary_stage_ref:ref,canonical_name:'New Stage',purpose:'Describe this stage',proposed_order:localStages.length+1,proposed_start:workspace.event.starts_at,proposed_end:workspace.event.ends_at,dependencies:[]});selectedRef=ref;render()};
document.querySelector('#delete-stage').onclick=()=>{if(localStages.length===1)return showError(new Error('A stage plan requires at least one stage.'));localStages=localStages.filter(s=>s.temporary_stage_ref!==selectedRef);localStages.forEach(s=>s.dependencies=s.dependencies.filter(d=>d!==selectedRef));selectedRef=localStages[0].temporary_stage_ref;render()};
document.querySelector('#reset-plan').onclick=()=>{localStages=clone(original.proposed_stages);selectedRef=localStages[0]?.temporary_stage_ref;render()};
document.querySelector('#fit-view').onclick=()=>document.querySelector('.timeline-scroll').scrollTo({left:0,behavior:'smooth'});
document.querySelector('#confirm-stages').onclick=async()=>{const button=document.querySelector('#confirm-stages');button.disabled=true;try{const edited={...clone(original),proposed_stages:localStages.map((s,i)=>({...s,proposed_order:i+1}))};await api(`/stage-proposals/${workspace.proposal.id}/decision`,{method:'POST',body:JSON.stringify({decision:'APPROVE',decision_idempotency_key:`stage-approval:${workspace.proposal.id}`,edited_payload:edited})});location.reload()}catch(error){showError(error);button.disabled=false}};
function showError(error){const host=document.querySelector('#workspace-message');if(host)host.textContent=error.message;else document.body.textContent=error.message}
initialize();
installSaveExit(eventId, 'STAGE_PLANNING');
